### ISSUE TITLE
option to extend Entity class?

### ISSUE THREAD

**Issue by Hectate** [kutuluk/js13k-ecs#4]
I'm using js13k-ecs in a roguelike project for pretty much everything in the game. It's going along great but I ran into a little hurdle that I hadn't quite decided how to overcome. Basically, I created a set of Entity classes that collected all the necessary bits and threw them into the ECS for me during the constructor. Essentially freeing me up to simply put down `let player = new Player(...);` and end up with everything in place.
All fine and dandy until I realized that my `player` object was not a part of the Entity class itself and therefore would need constant workaround of stuff like `player.entity` to access the ECS belonging to the object, and by extension any related components.
To simplify, I thought I could extend the js13k-ecs `Entity` class so that the `Player` class would play well (hah) with the ECS directly. Sadly, the Entity class is not exported so that's not possible.

What I'm curious about is, am I breaking something or doing something wrong if I simply added the export keyword to the `Entity` class in my version (and, should we add it to the entire module this way)? I'm self-taught at JS and it's entirely possible that I've missed something obvious. I appreciate any feedback you have. Thanks.

**Comment by Hectate** [comment]
I think I just rubber-ducked this by typing all this out and then thinking it over. I'd forgotten that an Entity should be nothing but an ID for components and systems to utilize. Because my Entity had grown beyond that it wasn't working quite right with what I was doing so I wanted to extend Entity. Having realized this, I am going to go back to my entities and fix them so they don't have behavior or data in them; leaving that for components and systems.
Maybe there's a reason to make the Entity class extendable, if you think so it's worth discussing. I won't close this so you can consider it here, but I don't need anything specifically right now, thanks!

**Comment by kutuluk** [comment]
That's right. Entity is just a collection of components with a unique id. Extend the entity is not necessary. Never. Otherwise, it will cease to be ECS.

**Comment by kutuluk** [comment]
I want to warn that the current implementation has a limit of 32 registered components. This is done to simplify and reduce the size of the code. If you reach this limit, write me and I will make an extended version. I also want to remind you that ecs is an antipode for object-oriented programming and was designed to solve its problems. And using ecs mixed with oop doesn't usually lead to anything good.

**Comment by Hectate** [comment]
Thanks for clarifying both the entity thing; I wasn't really going OOP as a route - up until the point I thought that extending the class would help me out. Now that I've started to refactor that back out I think I'll be set as a proper ECS should be
Thanks also for mentioning the component limit. I'm still in the early stages so I've not gotten anywhere near that limit. I'll evaluate my design and carefully consider what components are necessary to see if I expect to exceed 32. Given that it's a relatively simple roguelike that I'm using to self-educate, I doubt it will be a concern at the time.

I would recommend mentioning that in the Readme file so users are aware of the limit. I certainly would not have known (though in retrospect, I can see why it would be so).
